#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := sensor_server

EXTRA_COMPONENT_DIRS := $(IDF_PATH)/examples/bluetooth/esp_ble_mesh/common_components/example_init
EXTRA_COMPONENT_DIRS := /Users/Kuba/Documents/esp-idf/TEST1/esp-idf-lib/components
include $(IDF_PATH)/make/project.mk
